### ISSUE TITLE
Add guidance for actions to take on 404 page

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#137]
**What would you like to be added**:
It is suggested to include a behavior guide or action recommendations on the 404 error page. The guide should provide users with clear instructions on what steps to take when encountering a 404 "Not Found" page. This will help users navigate back to the desired content or find alternative resources.

**Why is this needed**:
The 404 error page can be frustrating and confusing for users, especially when they are unable to find the information they are looking for. By providing a behavior guide or action recommendations, we can assist users in resolving the issue more effectively and improve their overall experience on our platform.

**Additional Information**:
You can refer to the article [UX Design and Development 3. 404 Not found](https://brunch.co.kr/@hjjju/7) for insights and examples on how to design a helpful and user-friendly 404 error page.

**Comment by KimKyuHoi** [comment]
Could I try this Issue? It's interesting!

**Comment by devleejb** [comment]
@KimKyuHoi 
Of course! It would be a good idea to discuss how we plan to structure it before proceeding with the implementation. Do you have any ideas?

**Comment by KimKyuHoi** [comment]
@devleejb 
I'm not sure about the design yet, but when you access the 404 error page, you will be moved to the main page. The message "Invalid page. Move to the main page" will be displayed, and after 5 seconds, you will be moved using the Navigator (-1).
In the design section, a cute yorkie image is used when a 404 error occurs on the yorkie.team.github.io page. How about applying this?

**Comment by KimKyuHoi** [comment]
@devleejb 
And in the case of error pages, we plan to add a separate 404 error page component by inserting it into errorElement in the index router. How about this part?

**Comment by devleejb** [comment]
@KimKyuHoi 
Using the Yorkie image seems like a good idea. However, considering the typical behavior of a 404 page, it might not be necessary to provide automatic redirection to the previous page. Instead, how about providing this feature as a button?

Providing the `errorElement` of `react-router` is very good. However, since the URL of the current Workspace page is "/:workspaceSlug", the errorElement might not be rendered when the Workspace does not exist. It is necessary to choose an appropriate option considering this point.

**Comment by KimKyuHoi** [comment]
@devleejb 
Hmm, then I read the code and found a problem in the DocumentIndex Function where the 404 page was not redirected properly due to API communication in useGetWorkspaceQuery and useGetDocumentQuery. Taking advantage of this, what do you think about returning to a 404 error page when these queries produce an error? If the header part is visible because of the outlet, I plan to make it invisible through global state management.

**Comment by KimKyuHoi** [comment]
@devleejb 
Ah, after looking into it again, I think I can just search for the query in useGetWorkSpace and then return from the component if a 404 error appears. I think it will probably be done in the WorkspacIndex Function, so why not do a code review while first making a PR?

**Comment by devleejb** [comment]
@KimKyuHoi 
That's a good suggestion.

How about creating a shared `/404` page (not returning 404 component in previous page) and calling `navigate("/404")` when the API response is 404 within useGetWorkSpaceQuery and useGetDocumentQuery?

It might also be helpful to discuss while looking at the PR code as you mentioned.

**Comment by KimKyuHoi** [comment]
@devleejb 

Oh, I was considering that too, I think it's a great idea! And looking at the CodePairError component, it looks like it will be produced with MUI instead of the Yorkie image, considering design unity.

Oh, and in the case of :workspaceSlug/:documentId, if an error occurs in :documentId after accessing :workspaceSlug normally, a 500 error is displayed instead of a 404 error. First, if a 500 error occurs, a 404 page will be displayed, but on the server side, When 404status is added in the future, it seems necessary to change it to navigate when the 404status condition is met.
